// Contenido del archivo CSV adjunto, incrustado como una cadena de texto.
// Puedes actualizar esta cadena si tu archivo CSV cambia.
const CSV_DATA = `StorageLocation,Item,UofM,Qty,UofM2,Qty2,UofM3,Qty3
BEER BTL,BEER DRAFT Peroni,Gallon,19.2,,,,
BEER BTL,BEER DRAFT Bud Light,Gallon,16.48,,,,
BEER BTL,BEER DRAFT VS La Yuma,Gallon,0,,,,
BEER BTL,BEER DRAFT Goose Ipa Draft,Gallon,12.7,,,,
BEER BTL,BEER BTL Fat Tire,Bottle (12 OZ-fl),4,,,,
BEER BTL,BEER BTL Lagunitas Ipa,Bottle (12 OZ-fl),0,,,,
BEER BTL,BEER BTL La Rubia,Bottle (12 OZ-fl),69,,,,
BEER BTL,BEER BTL Heineken,Bottle (12 OZ-fl),124,,,,
BEER BTL,BEER BTL Estrella Damm,Bottle (11.2 OZ-fl),0,,,,
BEER BTL,BEER BTL Peroni 00,Bottle (11.2 OZ-fl),47,,,,
BEER BTL,BEER BTL Funky Buddha Floridian,Bottle (12 OZ-fl),29,,,,
BEER BTL,BEER BTL Peroni,Bottle (11.2 OZ-fl),0,,,,
BEER BTL,BEER DRAFT Stella Artois,Gallon,11.33,Liter,0,,
BEER BTL,BEER BTL Michelob Ultra,Bottle (12 OZ-fl),74,Bottle (16 OZ-fl),0,,
BEER BTL,BEER BTL Modelo Especial,Bottle (12 OZ-fl),99,Bottle (7 OZ-fl),0,,
BEER BTL,BEER BTL Corona,Bottle (12 OZ-fl),152,,,,
CHAMP/SPARK,CHAMP/SPARK Moet Imperial Brut,Bottle (750 ML),5,Bottle (187 mL),0,,
CHAMP/SPARK,CHAMP/SPARK Moet Ice Imperial,Bottle (750 ML),5,,,,
CHAMP/SPARK,CHAMP/SPARK Veuve Clicquot Rose,Bottle (750 ML),4,,,,
CHAMP/SPARK,CHAMP/SPARK Della Vite Pros,Bottle (750 ML),8,,,,
CHAMP/SPARK,CHAMP/SPARK Gioiosa Prosecco,Bottle (750 ML),18.1,,,,
CHAMP/SPARK,CHAMP/SPARK Le Contesse Prosecco,Bottle (750 ML),9,,,,
CHAMP/SPARK,CHAMP/SPARK House Sparkling,Bottle (750 ML),63.8,,,,
CON BAR,CON BAR Mix Bloody Mary,Bottle (32 OZ-fl),17,Can (7.5 OZ-fl),0,,
CON BAR,SODAS Diet Coke Can,Can (12 OZ-fl),0,Can (7 OZ-fl),0,,
CON BAR,SODAS Diet Coke Btl,Bottle (8 OZ-fl),187,,,,
CON BAR,SODAS Coke Btl,Bottle (8 OZ-fl),166,,,,
CON BAR,SODAS Sprite Btl,Bottle (8 OZ-fl),38,Bottle (12 OZ-fl),0,,
CON BAR,CON BAR Grapefruit Soda,Bottle (6.7 OZ-fl),59,Bottle (12 OZ-fl),0,Can (7.5 OZ-fl),0
CON BAR,SODAS Ginger Ale,Can (12 OZ-fl),0,Can (7.5 OZ-fl),0,Bottle (6.7 OZ-fl),58
CON BAR,CON BAR Ginger Beer,Bottle (6.7 OZ-fl),83,Bottle (16.9 OZ-fl),0,Can (7.5 OZ-fl),0
CON BAR,CON BAR Tonic Water,Bottle (6.7 OZ-fl),73,Can (7.5 OZ-fl),0,Bottle (12 OZ-fl),0
CON BAR,CON BAR Club Soda,Bottle (6.7 OZ-fl),126,Bottle (12 OZ-fl),0,Can (7.5 OZ-fl),0
CON BAR,SODAS Red Bull,Bottle (8.4 OZ-fl),44,Bottle (12 OZ-fl),0,,
CON BAR,SODAS Red Bull Sugar Free,Bottle (8.4 OZ-fl),18,Bottle (12 OZ-fl),0,,
CON BAR,SODAS Red Bull Yellow,Bottle (8.4 OZ-fl),44,,,,
CON BAR,WATER BTL Panna Water Lg,Bottle (1 Litre),221,Bottle - 750 ML,0,,
CON BAR,WATER BTL San Pellegrino Lg,Bottle (1 Litre),135,,,,
CON BAR,CON BAR Mix Strawberry,Bottle (32 OZ-fl),0,Bottle (16.9 OZ-fl),5,,
CON BAR,CON BAR Mix Passion Fruit,Bottle (32 OZ-fl),0,Bottle (17 OZ-fl),1,,
CON BAR,CON BAR Mix Mango,Bottle (32 OZ-fl),0,Bottle (16.9 OZ-fl),2,Bottle (1 Litre),0
CON BAR,CON BAR Mix Peach,Bottle (16.9 OZ-fl),3,Bottle (32 OZ-fl),0,,
CON BAR,CON BAR Mix Kiwi,Bottle (32 OZ-fl),0,Bottle (16.9 OZ-fl),8,,
CON BAR,CON BAR Mix Rose Syrup,Bottle (1 Litre),0,Bottle (750 ML),0,,
CON BAR,COFFEE Syrup Vanilla,Litre,3.7,Bottle (16.9 OZ-fl),0,,
CON BAR,COFFEE Syrup Hazelnut,Bottle (750 ML),0,Bottle (1 Litre),1.2,,
CON BAR,COFFEE Syrup Chocolate,Bottle (24 OZ-fl),17,Bottle (16 OZ-fl),0,Bottle (64 OZ-fl),0
CON BAR,CON BAR Mix Citrus,Bottle (1 Litre),0,Bottle (64 OZ-fl),2,Bottle (32 OZ-fl),0
CON BAR,CON BAR Mix Pina Colada,Bottle (64 OZ-fl),0,Bottle (16.9 OZ-fl),0,Bottle (32 OZ-fl),0
CON BAR,CON BAR Nectar Agave,Jug (114 OZ-fl),0,lb,0,Gallon,0.7
CON BAR,CON BAR Queen Olives,Gal,1.1,Pack (64 OZ-wt),0,,
CON BAR,CON BAR Black Cherries,Bottle (44 OZ-fl),0,0.5 Gallon,0,Case - 8 OZ-wt,0
CON BAR,CON BAR Lychee In Heavy Syrup,Bottle (20 OZ-fl),7,,,,
CON BAR,CON BAR Mint,lb,1.1,,,,
CON BAR,CON BAR Garnish Lime,SLICE,0,Bag - 500 Slices,0,,
CON BAR,CON BAR Garnish Lemon,SLICE,0,Bag - 500 Slices,0,,
CON BAR,CON BAR Garnish Orange,SLICE,0,Bag - 500 Slices,0,,
CON BAR,CON BAR Garnish Pineapple,SLICE,0,Bag - 500 Slices,0,,
CON BAR,CON BAR Garnish Grapefruit,SLICE,0,Bag - 500 Slices,0,,
CON BAR,CON BAR Garnish Strawberry,SLICE,0,Bag - 500 Slices,0,,
CON BAR,CON BAR Bitter Aromatic,Bottle (4 OZ-fl),0,Bottle (16 OZ-fl),0.3,Bottle (6.7 OZ-fl),0
CON BAR,CON BAR Bitter Orange,Bottle (200 mL),0,Bottle (4 OZ-fl),0.5,,
CON BAR,CON BAR Bitter Peychaud's,Bottle (200 mL),4.2,,,,
CON BAR,CON BAR Fee Foam,Bottle (150 mL),0.2,Bottle (200 mL),0,,
CON BAR,CON BAR Mix Peach,Bottle (16.9 OZ-fl),0,Bottle (32 OZ-fl),0,,
CON BAR,CAN DRY Vanilla Extract,Bottle (32 OZ-fl),0,Gallon,0,,
CON BAR,CAN DRY Tajin,Jar - 5.3 OZ-wt,0,,,,
CON BAR,CON BAR Mix Rose Water,Bottle (10 OZ-fl),0,,,,
CON BAR,CON BAR Garnish Drink Topper,PC,0,,,,
CON BAR,CON BAR Olive Brine,Bottle (12 OZ-fl),0,,,,
CON BAR,CON BAR Mix Kiwi,Bottle (32 OZ-fl),0,Bottle (16.9 OZ-fl),0,,
CON BAR,CON BAR Rose Petals,Case - 1000 PC,0,,,,
CON BAR,CON BAR Mix Mango,Bottle (32 OZ-fl),0,Bottle (16.9 OZ-fl),0,Bottle (1 Litre),0
CON BAR,CON BAR Mix Pomegranate Basil,Bottle (1 Litre),0,Bottle (200 mL),0,,
CON BAR,CON BAR Mix Passion Fruit,Bottle (32 OZ-fl),0,Bottle (17 OZ-fl),0,,
CON BAR,CON BAR Mix Orange Tangerine,Bottle (1 Litre),0,,,,
CON BAR,PROD/FRT Orange,Orange,0,,,,
CON BAR,CON BAR Mix Grenadine,Bottle (1 Litre),0,,,,
CON BAR,CON BAR Puree Lychee,Bottle (16.9 OZ-fl),2,lb,0,Bottle (16.9 OZ-fl),0
CON BAR,SODAS Coke Can,Can (12 OZ-fl),0,,,,
CON BAR,SODAS Coke Can,Can (12 OZ-fl),36,,,,
CORDIALS,CORDIALS Lillet Blanc,Bottle (750 ML),4,,,,
CORDIALS,CORDIALS Lillet Rose,Bottle (750 ML),8,,,,
CORDIALS,CORDIALS Grand Marnier,Bottle (1 Litre),5.9,Bottle (750 ML),0,,
CORDIALS,CORDIALS Cointreau,Bottle (750 ML),0,Bottle (1 Litre),3.4,,
CORDIALS,CORDIALS Disaronno Amaretto,Bottle (750 ML),0,Bottle (1 Litre),1.7,,
CORDCIALS,CORDIALS Frangelico,Bottle (1 Litre),2,Bottle (750 ML),0,,
CORDIALS,CORDIALS Luxardo Maraschino,Bottle (750 ML),2.3,,,,
CORDIALS,CORDIALS Italicus Rosolio Bergamoto,Bottle (750 ML),1.8,,,,
CORDIALS,CORDIALS Creme De Mure,Bottle (750 ML),0,Bottle (700 mL),1.6,,
CORDIALS,CORDIALS Fernet Branca,Bottle (750 ML),2.1,,,,
CORDIALS,CORDIALS Sambuca Ramazzotti,Bottle (750 ML),1.7,,,,
CORDIALS,CORDIALS Chartreuse Green,Bottle (750 ML),0.4,,,,
CORDIALS,CORDIALS Caravedo Pisco Puro,Bottle (750 ML),1.25,,,,
CORDIALS,CORDIALS Campari Aperitivo,Bottle (1 Litre),1.7,Bottle - 750 ML,0,,
CORDIALS,CORDIALS Aperol Aperitivo,Bottle (750 ML),0,Bottle (1 Litre),3.8,,
CORDIALS,CORDIALS Giffard Banana Du Brazil,Bottle (750 ML),5.6,,,,
CORDIALS,CORDIALS Chinola Passion Fruit,Bottle (750 ML),4.2,,,,
CORDIALS,CORDIALS Creme De Pamplemousse,Bottle (750 ML),0.9,,,,
ORDIALS,CORDIALS Lo - Fi Amaro,Bottle (750 ML),1.7,,,,
CORDIALS,CORDIALS Botanical Rockey,Bottle (750 ML),3,Bottle (1 Litre),0,,
CORDIALS,CORDIALS Mandarine Napoleon,Bottle (1 Litre),4.8,Bottle (750 ML),0,,
CORDIALS,CORDIALS Amaro Montenegro,Bottle (750 ML),0,Bottle (1 Litre),4.2,,
CORDIALS,CORDIALS Liqueur Triple Sec,Bottle (1 Litre),6.5,Bottle (750 ML),0,,
CORDIALS,CORDIALS Schnapps Peach,Bottle (1 Litre),1.5,Bottle (750 ML),0,Bottle (1.75 Litre),0
CORDIALS,CORDIALS Vermouth Rosso/Rouge,Bottle (1 Litre),2,Bottle - 750 ML,0,Bottle (1.5 Litre),0
CORDIALS,CORDIALS Vermouth Dry,Bottle (1 Litre),0,Bottle (750 ML),2.3,,
CORDIALS,CORDIALS Remy Martin 1738,Bottle (1 Litre),1.8,Bottle (750 ML),0,,
CORDIALS,CORDIALS Hennessy VS,Bottle (1 Litre),1,Bottle (750 ML),0.7,Bottle (375 mL),0
CORDIALS,CORDIALS Kahlua,Bottle (1 Litre),3.3,Bottle (750 ML),0,,
CORDIALS,CORDIALS Creme De Cacao,Bottle (1 Litre),3.3,Bottle (750 ML),0,,
CORDIALS,CORDIALS Ancho Reyes Poblano Chile,Bottle (750 ML),0.2,,,,
CORDIALS,CORDIALS Ancho Reyes Ancho Chile,Bottle (750 ML),0.8,,,,
CORDIALS,CORDIALS Baileys Irish Cream,Bottle (1 Litre),2.2,Bottle (750 ML),0,,
CORDIALS,CORDIALS Benedictine,Bottle (1 Litre),9.3,Bottle (750 ML),0,,
CORDIALS,CORDIALS Licor 43,Bottle (1 Litre),1.3,Bottle (750 ML),0,,
CORDIALS,CORDIALS St Germain,Bottle (750 ML),4,,,,
CORDIALS,CORDIALS Blue Curacao,Bottle (1 Litre),2.1,,,,
GIN,GIN House,Bottle (1 Litre),8.1,Bottle (750 ML),0,,
GIN,GIN Atian,Bottle (750 ML),1.8,,,,
GIN,GIN Bombay Dry Gin,Bottle (1 Litre),2.4,Bottle (1.75 Litre),0,,
GIN,GIN Bombay Sapphire,Bottle (1 Litre),1.6,Bottle (750 ML),0,Bottle (1.75 Litre),0
GIN,GIN Harry Blus,Bottle (750 ML),14,,,,
GIN,GIN Hendricks,Bottle (1 Litre),2.7,Bottle - 750 ML,0,,
GIN,GIN Tanqueray,Bottle (1 Litre),2,,,,
GIN,GIN Fords,Bottle (750 ML),0,Bottle (1 Litre),1.2,,
GIN,GIN Monkey 47,Bottle (1 Litre),2.1,,,,
GIN,GIN Gray Whale,Bottle (750 ML),1.5,Bottle (1 Litre),0,,
GIN,GIN London No.3,Bottle (750 ML),3,Bottle (1 Litre),0,,
INFUSION,INFUSION Blueberry Hibiscus,Tea Bag,85,,,,
INFUSION,INFUSION Chamomile Tea,Tea Bag,83,lb,0,,
INFUSION,INFUSION English Breakfast,Tea Bag,41,,,,
INFUSION,INFUSION Jasmine Tea,Tea Bag,54,lb,0,,
INFUSION,INFUSION Matcha (tea bg),Tea Bag,92,,,,
INFUSION,INFUSION Turmeric Ginger Tea,Tea Bag,60,,,,
INFUSION,COFFEE Matcha (lb),lb,2.32,Case - 2.2 LB,0,,
INFUSION,INFUSION Iced Tea Org Black,Bag - 3 OZ-wt,22,,,,
WINE,RED WINE Cab Sauv Bonanza,Bottle (750 ML),14.4,,,,
WINE,RED WINE P Noir Elouan,Bottle (750 ML),3,,,,
WINE,RED WINE Malbec Aruma,Bottle (750 ML),0,,,,
WINE,RED WINE P Noir Belle Glos Las Alturas,Bottle (750 ML),6,,,,
WINE,RED WINE Red Blend Prisoner,Bottle (750 ML),4,,,,
WINE,RED WINE Merlot Decoy by Duckhorn,Bottle (750 ML),0,,,,
WINE,RED WINE Chianti Classico Collazzi,Bottle (750 ML),4,,,,
WINE,RED WINE Cab Sauv The Quilt Rsv,Bottle (750 ML),5,,,,
WINE,ROSE WINE The Pale Rose,Bottle (750 ML),0,,,,
WINE,ROSE Wine Whispering Angel,Bottle (750 ML),15.1,,,,
WINE,WHITE WINE Chardonnay Sea Sun,Bottle (750 ML),0,,,,
WINE,WHITE WINE Gavi Villa Sparina,Bottle (750 ML),8.9,,,,
WINE,WHITE WINE Riesling Chateau St Michelle,Bottle (750 ML),5.1,,,,
WINE,WHITE WINE Sauv Blanc Justin,Bottle (750 ML),9.9,,,,
WINE,WHITE WINE Sauv Blanc Dashwood,Bottle (750 ML),3,,,,
WINE,WHITE WINE Moscato D Asti  Saracco,Bottle (750 ML),8,,,,
WINE,WHITE WINE Chardonnay Landmark Sonoma,Bottle (750 ML),4,,,,
WINE,WHITE WINE P Grigio La Vis,Bottle (750 ML),3,,,,
WINE,WHITE WINE P Grigio Venezie Canaletto,Bottle (750 ML),8.1,,,,
WINE,RED WINE Malbec Antigal Uno,Bottle (750 ML),2,,,,
WINE,RED WINE Merlot Ca Donini,Bottle (750 ML),10.1,,,,
WINE,RED WINE P Noir Sea Sun,Bottle (750 ML),9.5,,,,
WINE,RED WINE Malbec Rsv Terraza,Bottle (750 ML),4.6,,,,
WINE,RED WINE Marques De Riscal Proximo,Bottle (750 ML),0,,,,
WINE,RED WINE Cab Sauv Justin,Bottle (750 ML),0,,,,
WINE,WHITE WINE Albarino Lusco,Bottle (750 ML),0,,,,
WINE,CHAMP/SPARK Veuve Du Vernay Brut Rose,Bottle (750 ML),0,,,,
WINE,CHAMP/SPARK Moet Imperial Brut,Bottle (750 ML),0,Bottle (187 mL),0,,
WINE,CHAMP/SPARK Chandon Sparkling,Bottle (750 ML),10,,,,
WINE,CHAMP/SPARK Veuve Clicquot Rose,Bottle (750 ML),0,,,,
WINE,CHAMP/SPARK Moet Ice Imperial,Bottle (750 ML),0,,,,
WINE,RED WINE Chianti Cafaggio,Bottle (750 ML),0,,,,
WINE,WHITE WINE Sauv Blanc Vavasour,Bottle (750 ML),12.5,,,,
WINE,RED WINE Tempranillo Numanthia Termes,Bottle (750 ML),6.1,,,,
WINE,WHITE WINE Chardonnay Elouan,Bottle (750 ML),12.5,,,,
RUM,RUM House,Bottle (1 Litre),0,Bottle (750 ML),0,,
RUM,RUM Bacardi Superior,Bottle (1 Litre),12.05,Bottle (1.75 Litre),0,Bottle - 750 ML,0
RUM,RUM Flor De Cana 4Yr Anejo Oro,Bottle (1 Litre),3.8,,,,
RUM,RUM Copalli Cacao,Bottle (750 ML),2,,,,
RUM,RUM Santa Teresa 1796,Bottle (750 ML),2.2,Bottle (1 Litre),0,,
RUM,RUM Sailor Jerry Spiced Rum,Bottle (1 Litre),3.7,Bottle - 750 ML,0,Bottle (1.75 Litre),0
RUM,RUM Coconut Cartel,Bottle (750 ML),1.1,,,,
RUM,RUM Leblon Cachaca,Bottle (1 Litre),0,Bottle (750 ML),0,,
RUM,RUM Plantation Pineapple,Bottle (1 Litre),0,Bottle (750 ML),0.5,,
RUM,RUM Zacapa Rum Cent 23Yr,Bottle (750 ML),2.8,Bottle (1 Litre),0,,
RUM,RUM Bacardi 10 Yr,Bottle (750 ML),2.1,,,,
RUM,RUM Brugal 1888,Bottle (750 ML),0.8,,,,
RUM,RUM Bacardi Anejo 4 Yr,Bottle (750 ML),0.7,Bottle (1 Litre),1,,
RUM,RUM Piras 51 Cachaca,Bottle (1 Litre),2.7,,,,
RUM,RUM Flor De Cana 4Yr White Extra Seco,Bottle (1 Litre),0,,,,
RUM,RUM Nusa Cana Spiced,Bottle (700 mL),1,,,,
RUM,RUM Nusa Cana Tropical,Bottle (700 mL),1,,,,
RUM,RUM Bacardi Coco,Bottle (1 Litre),0,Bottle (750 ML),0,,
TEQUILA,TEQUILA Gran Coramino Reposado,Bottle (750 ML),1,,,,
TEQUILA,TEQUILA House,Bottle (1 Litre),18.8,Bottle (750 ML),0,,
TEQUILA,TEQUILA Jimador Silver,Bottle (1 Litre),9.9,Bottle (750 ML),0,Bottle (1.75 Litre),0
TEQUILA,TEQUILA 512 Blanco,Bottle (750 ML),0,Bottle (1 Litre),1.6,,
TEQUILA,TEQUILA 512 Reposado,Bottle (750 ML),1.3,,,,
TEQUILA,TEQUILA 512 Anejo,Bottle (750 ML),0.9,,,,
TEQUILA,TEQUILA Casamigos Blanco,Bottle (1 Litre),2.5,Bottle - 750 ML,0,Bottle (1 Litre),0
TEQUILA,TEQUILA Casamigos Reposado,Bottle (750 ML),0,Bottle (1 Litre),1.9,,
TEQUILA,TEQUILA Casamigos Anejo,Bottle (1 Litre),2,Bottle (750 ML),0,,
TEQUILA,TEQUILA Don Julio Blanco,Bottle (750 ML),1.9,Bottle (375 mL),0,,
TEQUILA,TEQUILA Don Julio Reposado,Bottle (750 ML),0.2,,,,
TEQUILA,TEQUILA Don Julio Anejo,Bottle (750 ML),1.5,,,,
TEQUILA,TEQUILA Don Julio 1942,Bottle (750 ML),1.25,Bottle (1.75 Litre),0,,
TEQUILA,TEQUILA Herradura Silver,Bottle (1 Litre),3.6,Bottle (750 ML),0,Bottle (1.75 Litre),0
TEQUILA,TEQUILA Herradura Reposado,Bottle (1 Litre),1.05,Bottle (750 ML),0,,
TEQUILA,TEQUILA Herradura Anejo,Bottle (750 ML),0.75,Bottle (1 Litre),0,,
TEQUILA,TEQUILA Herradura Ultra Anejo,Bottle (750 ML),0.6,,,,
TEQUILA,TEQUILA Patron Silver,Bottle (750 ML),2.5,Bottle (1 Litre),0,,
TEQUILA,TEQUILA Patron Reposado,Bottle (750 ML),3.1,,,,
TEQUILA,TEQUILA Patron Anejo,Bottle (750 ML),2.45,,,,
TEQUILA,TEQUILA Tromba Blanco,Bottle (750 ML),0,Bottle (1 Litre),5.1,,
TEQUILA,TEQUILA Dahlia Cristalino,Bottle (750 ML),1.75,,,,
TEQUILA,TEQUILA Mezcal Joven Ilegal,Bottle (1 Litre),1.5,Bottle (750 ML),0,,
TEQUILA,TEQUILA Mezcal Del Maguey Vida,Bottle (750 ML),1.15,,,,
TEQUILA,TEQUILA Mezcal El Silencio,Bottle (750 ML),0,,,,
TEQUILA,TEQUILA Jose Cuervo Reserva Familia Extra Anejo,Bottle (750 ML),1.5,,,,
TEQUILA,TEQUILA Mezcal Ojo de Tigre,Bottle (750 ML),1.3,Bottle (1 Litre),0,,
TEQUILA,TEQUILA 21 Seeds Cucumber Jalapeno,Bottle (750 ML),0,,,,
TEQUILA,TEQUILA 21 Seeds Grapefruit Hibiscus,Bottle (750 ML),0,,,,
TEQUILA,TEQUILA 21 Seeds Valencia Orange,Bottle (750 ML),0,,,,
TEQUILA,TEQUILA Volcan Tierra Blanco,Bottle (750 ML),0,,,,
TEQUILA,TEQUILA Volcan Tierra Rep,Bottle (750 ML),0,,,,
TEQUILA,TEQUILA Volcan Tierra Tahona,Bottle (750 ML),0,,,,
TEQUILA,TEQUILA Volcan Tierra XA,Bottle (750 ML),0,,,,
TEQUILA,TEQUILA Astral Anejo,Bottle (750 ML),0,,,,
TEQUILA,TEQUILA Astral Blanco,Bottle (750 ML),0,,,,
TEQUILA,TEQUILA Astral Reposado,Bottle (750 ML),0,,,,
TEQUILA,TEQUILA Pierde Almas Mezcal Espadin,Bottle (750 ML),0,,,,
TEQUILA,TEQUILA Pierde Almas Mezcal Purita,Bottle (750 ML),0,,,,
TEQUILA,TEQUILA Don Julio 1942 Alma Miel,Bottle (750 ML),0,,,,
TEQUILA,TEQUILA Gran Coramino Cristalino Reposado,Bottle (750 ML),1,,,,
VODKA,VODKA House,Bottle (750 ML),6.9,Bottle (750 ML),0,,
VODKA,VODKA Albani,Bottle (1 Litre),1,,,,
VODKA,VODKA Grey Goose,Bottle (1 Litre),3.7,Bottle (750 ML),0,,
VODKA,VODKA Titos,Bottle (1 Litre),4.3,Bottle (1.75 Litre),0,Bottle (750 ML),0
VODKA,VODKA Harry Blus,Bottle (750 ML),0.1,,,,
VODKA,VODKA Ketel One,Bottle (1 Litre),3.5,Bottle (1.75 Litre),0,Bottle (750 ML),0
VODKA,VODKA Ketel One Citroen,Bottle (1 Litre),1,Bottle (750 ML),0,,
VODKA,VODKA Organika Vodka,Bottle (1 Litre),8.4,Bottle (750 ML),0,,
VODKA,VODKA Belvedere,Bottle (1 Litre),2.35,,,,
VODKA,VODKA Absolut,Bottle (1 Litre),1.8,,,,
VODKA,VODKA Smirnoff Orange,Bottle (1 Litre),0,,,,
WHISKEY,WHISKEY Woodford Reserve,Bottle (1 Litre),2.1,Bottle (750 ML),0,,
WHISKEY,WHISKEY Old Forester Brbn 86,Bottle (1 Litre),2.5,Bottle (750 ML),0,Bottle (1.75 Litre),0
WHISKEY,WHISKEY Jack Daniels Single Barrel Rye,Bottle (1 Litre),6.1,,,,
WHISKEY,WHISKEY Jack Daniels Old 7 Blk,Bottle (1 Litre),3.05,Bottle (750 ML),0,,
WHISKEY,WHISKEY Jack Daniels Fire,Bottle (750 ML),2.5,,,,
WHISKEY,WHISKEY Crown Royal Canadian,Bottle (1 Litre),1,Bottle (750 ML),0.9,,
WHISKEY,WHISKEY Crown Royal Apple,Bottle (1 Litre),1.8,,,,
WHISKEY,WHISKEY Jameson,Bottle (1 Litre),1,Bottle (750 ML),0.8,,
WHISKEY,WHISKEY Slane Irish,Bottle (1 Litre),1.3,Bottle - 750 ML,0,,
WHISKEY,WHISKEY Angels Envy Bourbon,Bottle (750 ML),2.5,Bottle (1 Litre),0,,
WHISKEY,WHISKEY Angels Envy Rye,Bottle (750 ML),2.2,,,,
WHISKEY,WHISKEY Dewars White,Bottle (1 Litre),6.7,Bottle (750 ML),0,,
WHISKEY,WHISKEY J Walker Black,Bottle (1 Litre),1.6,Bottle (750 ML),0,,
WHISKEY,WHISKEY Balvenie Scotch 12 Yr Doublewood,Bottle (750 ML),1.5,,,,
WHISKEY,WHISKEY Makers Mark,Bottle (1 Litre),1.5,Bottle (750 ML),0,,
WHISKEY,WHISKEY Buchanans 12 Yr,Bottle (750 ML),0,Bottle (1 Litre),1.7,,
WHISKEY,WHISKEY Chivas Regal 12 Yr,Bottle (1 Litre),1.3,Bottle (750 ML),0,,
WHISKEY,WHISKEY Old Parr Scotch 12 Yr,Bottle (750 ML),1.7,,,,
WHISKEY,WHISKEY Glenfiddich 12 Yr,Bottle (1 Litre),2,Bottle (750 ML),0.3,,
WHISKEY,WHISKEY Glenlivet 12 Yr,Bottle (1 Litre),0,Bottle - 750 ML,2.8,,
WHISKEY,WHISKEY Macallan 12 Yr,Bottle (750 ML),1.8,Bottle (1 Litre),0,,
Bar Prep,PREP NEWS - Frozzie Rosie,QT,20,OZ-fl,0,,
Bar Prep,PREP NEWS - Just Like 1988,QT,15,,,,
Bar Prep,PREP NEWS - Spicy Agave,OZ-fl,0,QT,0,,
Bar Prep,PREP NEWS - Blue Citrus Reduction,QT,0,OZ-fl,0,,
Bar Prep,PREP NEWS - Demerara Syrup,OZ-fl,0,QT,0,,
Bar Prep,PREP MRB - Simple Syrup,Bottle (32 OZ-fl),0,Bottle (1 Litre),0,,
Juices,CAN DRY Juice Lime,Bottle (59 OZ-fl),5,Bottle (59 OZ-fl),0,Bottle (750 ML),0
Juices,CAN DRY Juice Lemon,Bottle (59 OZ-fl),1.3,Gal,0,Bottle (750 ML),0
Juices,JUICES Juice Orange,Bottle (59 OZ-fl),36,Gal,0,Gallon,0
Juices,CON BAR Juice Grapefruit,Bottle (32 OZ-fl),12.7,Gal,0,Bottle (32 OZ-fl),0
Juices,CON BAR Juice Cranberry,Bottle (32 OZ-fl),18.2,Bottle (64 OZ-fl),0,Bottle (5.5 OZ-fl),0
Juices,JUICES Juice Apple,Bottle (32 OZ-fl),15.7,Gal,0,Bottle (46 OZ-fl),0
Juices,CON BAR Juice Pineapple,Can (6 OZ-fl),0,Bottle (46 OZ-fl),9.4,Can (5.5 OZ-fl),0
Juices,JUICES Juice Unbeetable Cold Pressed,Bottle (12 OZ-fl),23,,,,
Juices,JUICES Juice Sunset Cold Pressed,Bottle (12 OZ-fl),40,,,,
Juices,JUICES Juice Green Lover Cold Pressed,Bottle (12 OZ-fl),37,,,,
Coffee,COFFEE Milk Soy,Bottle (32 OZ-fl),14.6,Bottle (64 OZ-fl),0,,
Coffee,COFFEE Milk Oat,Bottle (32 OZ-fl),25.2,,,,
Coffee,COFFEE Milk Almond,Bottle (32 OZ-fl),16,Gal,0,Bottle (64 OZ-fl),0
Coffee,COFFEE Milk Whole,Gal,30.5,Bottle (32 OZ-fl),0,Gallon,0
Coffee,COFFEE Half n Half,0.5 Gallon,6.35,,,,
Coffee,COFFEE Kimbo Decaf Coffee Filtro Ground,Pack (8 OZ-wt),0,Packet (2.25 OZ-wt),0,,
Coffee,COFFEE Kimbo Coffee Filtro Ground,Pack (8 OZ-wt),48,Packet (2.25 OZ-wt),0,,
Coffee,COFFEE Kimbo Decaf Espresso Beans,lb,0.7,,,,
Coffee,COFFEE Kimbo Extra Cream Espresso Beans,lb,15.4,,,,
Coffee,PREP MRB - Caramel Syrup,OZ-fl,0,,,,
Coffee,COFFEE Syrup Caramel,Bottle (44 OZ-fl),0,Bottle (64 OZ-fl),0,Bottle (1 Litre),3.8
BEER Taco Shop,BEER BTL Blue Moon,Bottle (12 OZ-fl),50,,,,
BEER Taco Shop,BEER BTL Corona,Bottle (12 OZ-fl),152,,,,
BEER Taco Shop,BEER BTL Corona Light,Bottle (12 OZ-fl),66,,,,
BEER Taco Shop,BEER BTL Dos Xx Amber,Bottle (12 OZ-fl),97,,,,
BEER Taco Shop,BEER BTL Dos Xx Lager,Bottle (12 OZ-fl),98,,,,
BEER Taco Shop,BEER BTL Heineken,Bottle (12 OZ-fl),61,,,,
BEER Taco Shop,BEER BTL Lagunitas Ipa,Bottle (12 OZ-fl),46,,,,
BEER Taco Shop,BEER BTL Modelo Especial,Bottle (12 OZ-fl),116,Bottle (7 OZ-fl),0,,
BEER Taco Shop,BEER BTL Negra Modelo,Bottle (12 OZ-fl),70,,,,
BEER Taco Shop,BEER BTL Pacifico,Bottle (12 OZ-fl),133,,,,
BEER Taco Shop,BEER BTL Tecate Can,Bottle (12 OZ-fl),67,,,,
BEER Taco Shop,BEER BTL Tecate Light Can,Bottle (12 OZ-fl),83,,,,
BEER Taco Shop,BEER BTL Victoria,Bottle (12 OZ-fl),51,,,,
BAR CONS Taco Shop,CAN DRY Coconut Shredded Sweetened,lb,0,,,,
BAR CONS Taco Shop,CAN DRY Juice Lemon,Bottle (59 OZ-fl),0,Gal,0,Bottle (750 ML),0
BAR CONS Taco Shop,CAN DRY Juice Lime,Bottle (59 OZ-fl),0,Bottle (59 OZ-fl),0,Bottle (750 ML),0
BAR CONS Taco Shop,CAN DRY Tajin,Jar - 5.3 OZ-wt,11,,,,
BAR CONS Taco Shop,CON BAR Agua Tamarindo,Bottle (32 OZ-fl),4.2,,,,
BAR CONS Taco Shop,CON BAR Bitter Aromatic,Bottle (4 OZ-fl),0,Bottle (16 OZ-fl),4.7,Bottle (6.7 OZ-fl),0
BAR CONS Taco Shop,CON BAR Bitter Orange,Bottle (200 mL),0,Bottle (4 OZ-fl),1,,
BAR CONS Taco Shop,CON BAR Bitter Peychaud's,Bottle (200 mL),4,,,,
BAR CONS Taco Shop,CON BAR Black Cherries,Bottle (44 OZ-fl),0,0.5 Gallon,0,Case - 8 OZ-wt,0
BAR CONS Taco Shop,CON BAR Chamoy,Bottle (1 Litre),7.3,,,,
BAR CONS Taco Shop,CON BAR Cherry Maraschino,Gallon,0.4,Can - 3 Kg,0,Case - 8 OZ-wt,0
BAR CONS Taco Shop,CON BAR Coconut Water,Bottle (11.1 OZ-fl),35,Bottle (1 Litre),0,,
BAR CONS Taco Shop,CON BAR Coke Bib,Gallon,5.5,Keg (2.5 Gl),0,,
BAR CONS Taco Shop,CON BAR Dragon Fruit Chunks,lb,15,,,,
BAR CONS Taco Shop,CON BAR Edible Flowers,Flower,0,,,,
BAR CONS Taco Shop,CON BAR Fee Foam,Bottle (150 mL),0.6,Bottle (200 mL),0,,
BAR CONS Taco Shop,CON BAR Garnish Dragonfruit,SLICE,0,Bag - 500 Slices,0,,
BAR CONS Taco Shop,CON BAR Garnish Grapefruit,SLICE,0,Bag - 500 Slices,0,,
BAR CONS Taco Shop,CON BAR Garnish Kiwi,SLICE,0,Bag - 500 Slices,0,,
BAR CONS Taco Shop,CON BAR Garnish Lime,SLICE,0,Bag - 500 Slices,0,,
BAR CONS Taco Shop,CON BAR Garnish Orange,SLICE,0,Bag - 500 Slices,0,,
BAR CONS Taco Shop,CON BAR Garnish Pineapple,SLICE,0,Bag - 500 Slices,0,,
BAR CONS Taco Shop,CON BAR Ginger Beer,Bottle (6.7 OZ-fl),11,Bottle (16.9 OZ-fl),0,Can (7.5 OZ-fl),0
BAR CONS Taco Shop,CON BAR Juice Clamato,Bottle (1 Litre),2,Bottle (8 OZ-fl),0,,
BAR CONS Taco Shop,CON BAR Juice Cranberry,Bottle (32 OZ-fl),1.4,Bottle (64 OZ-fl),0,Bottle (5.5 OZ-fl),0
BAR CONS Taco Shop,CON BAR Juice Cranberry Bib,Gallon,0,Keg (2.5 Gl),0,,
BAR CONS Taco Shop,CON BAR Juice Pineapple,Can (6 OZ-fl),73,Bottle (46 OZ-fl),0,Can (5.5 OZ-fl),0
BAR CONS Taco Shop,CON BAR Maggi Seasoning Liquid,Bottle (27 OZ-fl),1.7,,,,
BAR CONS Taco Shop,CON BAR Mint,lb,3.1,,,,
BAR CONS Taco Shop,CON BAR Mix Bloody Mary,Bottle (32 OZ-fl),0,Can (7.5 OZ-fl),0,,
BAR CONS Taco Shop,CON BAR Mix Grenadine,Bottle (1 Litre),0.9,,,,
BAR CONS Taco Shop,CON BAR Mix Mango,Bottle (32 OZ-fl),13.7,Bottle (16.9 OZ-fl),0,Bottle (1 Litre),0
BAR CONS Taco Shop,CON BAR Mix Passion Fruit,Bottle (32 OZ-fl),19.2,Bottle (17 OZ-fl),0,,
BAR CONS Taco Shop,CON BAR Mix Pina Colada,Bottle (64 OZ-fl),0,Bottle (16.9 OZ-fl),0,Bottle (32 OZ-fl),19.3
BAR CONS Taco Shop,CON BAR Mix Strawberry,Bottle (32 OZ-fl),19.3,Bottle (16.9 OZ-fl),0,,
BAR CONS Taco Shop,CON BAR Nectar Agave,Jug (114 OZ-fl),0,lb,0,Gallon,0.3
BAR CONS Taco Shop,CON BAR Queen Olives,Gal,0.9,Pack (64 OZ-wt),0,,
BAR CONS Taco Shop,CON